apiVersion: v1
kind: Pod
metadata:
  name: redis-django
  labels:
    app: web
spec:
  containers:
    - name: key-value-store
      image: redis
      securityContext:
        runAsUser: 2000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      ports:
        - containerPort: 6379
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 100Mi

          