ignore:
  - "*.md"

functions:
  clone:
    - command: subprocess.exec
      type: setup
      params:
        command: "mkdir -p mongodb-kubernetes-operator"
    - command: git.get_project
      type: setup
      params:
        directory: mongodb-kubernetes-operator

  go_test:
    - command: subprocess.exec
      type: test
      params:
        add_to_path:
          - ${workdir}/bin
        working_dir: mongodb-kubernetes-operator
        command: "go test ./..."

  setup_operator_sdk:
    - command: subprocess.exec
      type: setup
      params:
        add_to_path:
          - ${workdir}/bin
        working_dir: mongodb-kubernetes-operator
        include_expansions_in_env:
          - workdir
        binary: scripts/ci/setup_operator_sdk.sh

  generate_k8s:
    - command: subprocess.exec
      type: setup
      params:
        add_to_path:
          - ${workdir}/bin
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/generate_k8.sh

tasks:
  - name: unit_tests
    commands:
      - func: clone
      - func: setup_operator_sdk
      - func: generate_k8s
      - func: go_test

buildvariants:
  - name: go_unit_tests
    display_name: go_unit_tests
    run_on:
      - archlinux-test
    stepback: false
    tasks:
      - name: unit_tests
