ignore:
  - "*.md"

functions:
  setup_virtualenv:
    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator
        command: "virtualenv --python /opt/python/3.7/bin/python3 ./venv"

  clone:
    - command: subprocess.exec
      type: setup
      params:
        command: "mkdir -p mongodb-kubernetes-operator"
    - command: git.get_project
      type: setup
      params:
        directory: mongodb-kubernetes-operator

  go_test:
    - command: subprocess.exec
      type: test
      params:
        include_expansions_in_env:
          - version_id
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/run_unit_tests.sh

  setup_operator_sdk:
    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator/scripts/ci
        command: go run download.go
        env:
          URL: https://github.com/operator-framework/operator-sdk/releases/download/v0.15.1/operator-sdk-v0.15.1-x86_64-linux-gnu
          FILENAME: operator-sdk
          DIR: ${workdir}/bin

  # upload_e2e_logs has the responsibility of dumping as much information as
  # posible into the S3 bucket 
  upload_e2e_logs:
    - command: s3.put
      params:
        aws_key: ${community_aws_access_key_id}
        aws_secret: ${community_aws_secret_access_key}
        local_files_include_filter_prefix: mongodb-kubernetes-operator/logs/
        local_files_include_filter:
          - e2e/*.txt
          - e2e/*.log
        region: us-east-1
        remote_file: logs/${task_id}/${execution}/
        bucket: community-operator-e2e-logs
        permissions: public-read
        content_type: text/plain


  setup_kubernetes_environment:
    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator/scripts/ci
        command: go run download.go
        env:
          URL: https://storage.googleapis.com/kubernetes-release/release/v1.15.4/bin/linux/amd64/kubectl
          FILENAME: kubectl
          DIR: ${workdir}/bin

    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator/scripts/ci
        command: go run download.go
        env:
          URL: https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64
          FILENAME: kind
          DIR: ${workdir}/bin

  create_kind_cluster:
    - command: subprocess.exec
      type: setup
      params:
        add_to_path:
          - ${workdir}/bin
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/create_kind_cluster.sh
        env:
          KUBECONFIG: ${workdir}/kube_config

  black_formatting_test:
    - command: shell.exec
      type: test
      params:
        working_dir: mongodb-kubernetes-operator
        script: . venv/bin/activate
            pip3 install black
            black --check `find . -type f -not -path '*venv*' -name '*.py'`

  run_e2e_test:
    - command: shell.exec
      type: test
      params:
        working_dir: mongodb-kubernetes-operator
        script: . venv/bin/activate
            pip3 install -r ./requirements.txt
            python3 ./scripts/dev/e2e.py --test ${test} --tag ${version_id} --config_file ./scripts/ci/config.json

  mypy_linting_test:
    - command: shell.exec
      type: test
      params:
        working_dir: mongodb-kubernetes-operator
        script: . venv/bin/activate
            pip3 install mypy
            find . -type f -name '*.py' -exec python3 -m mypy --ignore-missing-imports {} +


  build_and_push_image:
    - command: subprocess.exec
      type: setup
      params:
        include_expansions_in_env:
          - version_id
          - quay_user_name
          - quay_password
          - image
          - image_type
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/build_and_push_image.sh

task_groups:
- name: e2e_test_group
  max_hosts: 3
  setup_group:
    - func: clone
    - func: setup_virtualenv
    - func: setup_kubernetes_environment
  setup_task:
    - func: create_kind_cluster
  tasks:
    - e2e_test_replica_set
    - e2e_test_replica_set_readiness_probe
    - e2e_test_replica_set_scale
    - e2e_test_replica_set_change_version
    - e2e_test_feature_compatibility_version
    - e2e_test_feature_compatibility_version_upgrade
    - e2e_test_replica_set_multiple
  teardown_task:
    - func: upload_e2e_logs

tasks:
  - name: build_operator_image
    priority: 60
    exec_timeout_secs: 600
    commands:
      - func: clone
      - func: setup_virtualenv
      - func: build_and_push_image
        vars:
          image_type: operator
          image: quay.io/mongodb/community-operator-dev:${version_id}

  - name: build_e2e_image
    priority: 60
    exec_timeout_secs: 600
    commands:
      - func: clone
      - func: setup_virtualenv
      - func: build_and_push_image
        vars:
          image: quay.io/mongodb/community-operator-e2e:${version_id}
          image_type: e2e

  - name: build_prehook_image
    priority: 60
    exec_timeout_secs: 600
    commands:
      - func: clone
      - func: setup_virtualenv
      - func: build_and_push_image
        vars:
          image: quay.io/mongodb/community-operator-pre-stop-hook:${version_id}
          image_type: prehook

  - name: build_testrunner_image
    priority: 60
    exec_timeout_secs: 600
    commands:
      - func: clone
      - func: setup_virtualenv
      - func: build_and_push_image
        vars:
          image: quay.io/mongodb/community-operator-testrunner:${version_id}
          image_type: testrunner

  - name: black_formatting
    commands:
        - func: clone
        - func: setup_virtualenv
        - func: black_formatting_test

  - name: unit_tests
    commands:
      - func: clone
      - func: go_test


  - name: mypy_linting
    commands:
        - func: clone
        - func: setup_virtualenv
        - func: mypy_linting_test


  - name: e2e_test_feature_compatibility_version
    commands:
      - func: run_e2e_test
        vars:
          test: feature_compatibility_version

  - name: e2e_test_feature_compatibility_version_upgrade
    commands:
      - func: run_e2e_test
        vars:
          test: feature_compatibility_version

  - name: e2e_test_replica_set
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set

  - name: e2e_test_replica_set_readiness_probe
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set_readiness_probe

  - name: e2e_test_replica_set_scale
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set_scale

  - name: e2e_test_replica_set_change_version
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set_change_version

  - name: e2e_test_replica_set_multiple
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set_multiple

buildvariants:
  - name: go_unit_tests
    display_name: go_unit_tests
    run_on:
      - ubuntu1604-build
    tasks:
      - name: unit_tests

  - name: e2e_tests
    display_name: e2e_tests
    run_on:
      - ubuntu1604-build
    depends_on:
      - name: build_operator_image
        variant: init_test_run
      - name: build_e2e_image
        variant: init_test_run
      - name: build_prehook_image
        variant: init_test_run
      - name: build_testrunner_image
        variant: init_test_run
    tasks:
      - name: e2e_test_group

  - name: code_health
    display_name: code_health
    run_on:
      - ubuntu1604-build
    tasks:
      - name: mypy_linting
      - name: black_formatting

  - name: init_test_run
    display_name: init_test_run
    run_on:
      - ubuntu1604-build
    tasks:
      - name: build_operator_image
      - name: build_e2e_image
      - name: build_testrunner_image
      - name: build_prehook_image
