resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: mongodb-kubernetes-operator
  newName: quay.io/mongodb/mongodb-kubernetes-operator:0.5.0
- name: quay.io/mongodb/mongodb-kubernetes-operator
  newName: 268558157000.dkr.ecr.us-east-1.amazonaws.com/nideg/ubuntu/mongodb-kubernetes-operator
  newTag: latest
