apiVersion: v1
kind: Pod
metadata:
  name: test-runner
  labels:
    app: test-runner
spec:
  containers:
    - image: quay.io/chatton/test
      imagePullPolicy: Always
      name: test-runner
      command:
        - ./runner
        - --operatorImage
        - quay.io/chatton/mongodb-kubernetes-operator
        - --testImage
        - quay.io/chatton/e2e
  restartPolicy: Never
  serviceAccount: test-runner
