apiVersion: v1
kind: Pod
metadata:
  name: test-runner
  labels:
    app: test-runner
spec:
  containers:
    - image: quay.io/chatton/test
      imagePullPolicy: Always
      name: test-runner
      volumeMounts:
        - mountPath: /etc/config
          name: kube-config-volume
      command:
        - ./runner
        - --kubeconfig
        - /etc/config/kubeconfig
        - --namespace
        - default
        - --operatorImage
        - quay.io/chatton/mongodb-kubernetes-operator
  restartPolicy: Never
  serviceAccount: mongodb-kubernetes-operator
  volumes:
    - configMap:
        name: kube-config
      name: kube-config-volume
