apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodbs.mongodb.com
spec:
  group: mongodb.com
  names:
    kind: MongoDB
    listKind: MongoDBList
    plural: mongodbs
    singular: mongodb
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MongoDB is the Schema for the mongodbs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MongoDBSpec defines the desired state of MongoDB
          properties:
            featureCompatibilityVersion:
              description: FeatureCompatibilityVersion configures the feature compatibility
                version that will be set for the deployment
              type: string
            members:
              description: Members is the number of members in the replica set
              type: integer
            type:
              description: Type defines which type of MongoDB deployment the resource
                should create
              type: string
            version:
              description: Version defines which version of MongoDB will be used
              type: string
          required:
          - type
          - version
          type: object
        status:
          description: MongoDBStatus defines the observed state of MongoDB
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
