name: Run E2E
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - pipeline-argument: operator-ubi
          - pipeline-argument: version-post-start-hook-init
          - pipeline-argument: readiness-probe-init
          - pipeline-argument: agent-ubi
          - pipeline-argument: agent-ubuntu
          - pipeline-argument: e2e
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('requirements.txt') }}

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Push Development Images
        run: python pipeline.py --image-name ${{ matrix.pipeline-argument }} --release false
        env:
          MONGODB_COMMUNITY_CONFIG: "${{ github.workspace }}/scripts/ci/config.json"
          version_id: "${{ github.run_id }}"

  tests:
    runs-on: ubuntu-latest
    needs: [setup]
    strategy:
      matrix:
        include:
          - test-name: replica_set
            distro: ubuntu
          - test-name: replica_set
            distro: ubi
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('requirements.txt') }}

      - name: Install Python Dependencies
        run: pip install -r requirements.txt
      - uses: azure/setup-kubectl@v1
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.9.0"
      - run: kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
      - name: "Run Test"
        run: python3 ./scripts/dev/e2e.py --test ${{ matrix.test-name }} --tag ${{ github.run_id }} --config_file ./scripts/ci/config.json --distro ${{ matrix.distro }}
