name: Go

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Build
      run: go build -v ./...

    - name: Test pkg
      run: go test -v ./pkg/...

    - name: Test mongotester
      run: go test -v ./test/e2e/util/mongotester/...
