---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Kubelinter-check

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#


##############################################
# Start the job on all push and pull requests#
##############################################
on:
  push:
    branches:
    - master
    paths-ignore: 
    - docs/**
  pull_request:
    branches:
    - master
    paths-ignore:
    - docs/**
  workflow_dispatch: {}
jobs:

  build:
    name: Run Kube-linter check
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Install Kube-linter
      run: GO111MODULE=on go get golang.stackrox.io/kube-linter/cmd/kube-linter
      
    - name: Get the changed files
      uses: lots0logs/gh-action-get-changed-files@2.1.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: ls -R ${GITHUB_WORKSPACE}

    - name: Run the kube-linter script
      run: |
        # make file runnable, might not be necessary
        chmod +x "${GITHUB_WORKSPACE}/.github/script_kubelinter.sh"
        ${GITHUB_WORKSPACE}/.github/script_kubelinter.sh
