---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Kubelinter-check2

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#


##############################################
# Start the job on all push and pull requests#
##############################################
on:
  push:
    branches:
    - master
    paths-ignore: 
    - docs/**
  pull_request:
    branches:
    - master
    paths-ignore:
    - docs/**
  workflow_dispatch: {}
jobs:
  Kubelinter:
    name: Run Kube-linter check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Scan repo ./deploy/ with kube-linter
      uses: stackrox/kube-linter-action@v1
      with:
        directory: "deploy/"
        config: ${GITHUB_WORKSPACE}/.github/config_files/config_lint.yaml

    - name: Scan repo ./config/samples/ with kube-linter
      uses: stackrox/kube-linter-action@v1
      with:
        directory: config/samples
        config: ${GITHUB_WORKSPACE}/.github/config_files/config_lint.yaml
